version: '3'

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
    restart:
      always
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - celery
    restart:
      always
  celery:
    build: .
    command: celery -A ToDo worker -l info
    volumes:
      - .:/code
    links:
      - redis
    restart:
      always