# Generated by Django 3.0.6 on 2020-05-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='execution_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
